language: java
sudo: false
install: true
os:
 - linux
addons:
  sonarqube:
    token:
      secure: "67dd5c2de62ea1ae8d6d185f54e926b8e33b4c0f"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
      